//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalTransparencySystem.Modules.Settings
{
    public partial class AdminProfile
    {
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divMessage;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl msgIcon;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Image imgProfile;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblProfileInitial;
        protected global::System.Web.UI.WebControls.Label lblProfileName;
        protected global::System.Web.UI.WebControls.Label lblProfileRole;
        protected global::System.Web.UI.WebControls.Label lblProfileEmail;
        protected global::System.Web.UI.WebControls.FileUpload fuProfileImage;
        protected global::System.Web.UI.WebControls.Button btnRemoveImage;
        protected global::System.Web.UI.WebControls.TextBox txtFullName;
        protected global::System.Web.UI.WebControls.TextBox txtUsername;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.TextBox txtPhone;
        protected global::System.Web.UI.WebControls.DropDownList ddlDepartment;
        protected global::System.Web.UI.WebControls.Button btnSaveProfile;
        protected global::System.Web.UI.WebControls.TextBox txtCurrentPassword;
        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;
        protected global::System.Web.UI.WebControls.Button btnChangePassword;
        protected global::System.Web.UI.WebControls.HyperLink lnkLogoutProfile;
    }
}
