//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalTransparencySystem.Modules.Settings
{
    public partial class UserProfile
    {
        protected global::System.Web.UI.WebControls.Image imgProfile;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblInitials;
        protected global::System.Web.UI.WebControls.Literal litFullName;
        protected global::System.Web.UI.WebControls.Literal litEmail;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spanRole;
        protected global::System.Web.UI.WebControls.Literal litDepartment;
        protected global::System.Web.UI.WebControls.Literal litPhone;
        protected global::System.Web.UI.WebControls.Literal litJoinDate;
        protected global::System.Web.UI.WebControls.Image imgProfileUpload;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblUploadInitials;
        protected global::System.Web.UI.WebControls.FileUpload fuProfileImage;
        protected global::System.Web.UI.WebControls.Button btnUploadImage;
        protected global::System.Web.UI.WebControls.TextBox txtFullName;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.TextBox txtPhone;
        protected global::System.Web.UI.WebControls.DropDownList ddlDepartment;
        protected global::System.Web.UI.WebControls.Button btnSaveProfile;
        protected global::System.Web.UI.WebControls.Label lblProfileSuccess;
        protected global::System.Web.UI.WebControls.TextBox txtCurrentPassword;
        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;
        protected global::System.Web.UI.WebControls.Button btnChangePassword;
        protected global::System.Web.UI.WebControls.Label lblPasswordSuccess;
        protected global::System.Web.UI.WebControls.Label lblPasswordError;
        protected global::System.Web.UI.WebControls.TextBox txtNewEmail;
        protected global::System.Web.UI.WebControls.Button btnSendEmailCode;
        protected global::System.Web.UI.WebControls.Panel pnlEmailOtp;
        protected global::System.Web.UI.WebControls.Label lblEmailOtpSent;
        protected global::System.Web.UI.WebControls.TextBox txtEmailOtp;
        protected global::System.Web.UI.WebControls.Button btnConfirmEmail;
        protected global::System.Web.UI.WebControls.Label lblEmailChangeMessage;
    }
}
