//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalTransparencySystem.Modules.UserDecisions
{
    public partial class UserDecisions
    {
        protected global::System.Web.UI.WebControls.Literal litTotal;
        protected global::System.Web.UI.WebControls.Literal litProposed;
        protected global::System.Web.UI.WebControls.Literal litUnderReview;
        protected global::System.Web.UI.WebControls.Literal litApproved;
        protected global::System.Web.UI.WebControls.Literal litCompleted;
        protected global::System.Web.UI.WebControls.Button btnAll;
        protected global::System.Web.UI.WebControls.Button btnProposed;
        protected global::System.Web.UI.WebControls.Button btnUnderReview;
        protected global::System.Web.UI.WebControls.Button btnApproved;
        protected global::System.Web.UI.WebControls.Button btnCompleted;
        protected global::System.Web.UI.WebControls.Repeater rptDecisions;
        protected global::System.Web.UI.WebControls.Panel pnlNoDecisions;
    }
}
