//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalTransparencySystem.MasterPages
{
    public partial class AdminTopbar
    {
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl notifBadge;
        protected global::System.Web.UI.WebControls.LinkButton lnkMarkAllRead;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl notifList;
        protected global::System.Web.UI.WebControls.HyperLink lnkAllNotifications;
        protected global::System.Web.UI.WebControls.HyperLink lnkSettings;
        protected global::System.Web.UI.WebControls.Image imgUserAvatar;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblAvatarInitial;
        protected global::System.Web.UI.WebControls.Label lblUserName;
        protected global::System.Web.UI.WebControls.Label lblUserEmail;
        protected global::System.Web.UI.WebControls.Label lblUserRole;
        protected global::System.Web.UI.WebControls.HyperLink lnkProfile;
        protected global::System.Web.UI.WebControls.HyperLink lnkSettingsMenu;
        protected global::System.Web.UI.WebControls.HyperLink lnkLoginHistory;
        protected global::System.Web.UI.WebControls.HyperLink lnkLogout;
    }
}
