//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalTransparencySystem.MasterPages
{
    public partial class UserSidebar
    {
        protected global::System.Web.UI.WebControls.HyperLink lnkDashboard;
        protected global::System.Web.UI.WebControls.HyperLink lnkIdentity;
        protected global::System.Web.UI.WebControls.HyperLink lnkTaskWorkspaces;
        protected global::System.Web.UI.WebControls.HyperLink lnkClubs;
        protected global::System.Web.UI.WebControls.HyperLink lnkAssignments;
        protected global::System.Web.UI.WebControls.Label lblAssignmentCount;
        protected global::System.Web.UI.WebControls.HyperLink lnkConnect;
        protected global::System.Web.UI.WebControls.HyperLink lnkMyEvents;
        protected global::System.Web.UI.WebControls.Panel pnlEventActions;
        protected global::System.Web.UI.WebControls.HyperLink lnkCampusEvents;
        protected global::System.Web.UI.WebControls.HyperLink lnkCreateEvent;
        protected global::System.Web.UI.WebControls.HyperLink lnkProposeEvent;
        protected global::System.Web.UI.WebControls.HyperLink lnkMyMeetings;
        protected global::System.Web.UI.WebControls.HyperLink lnkFeedback;
        protected global::System.Web.UI.WebControls.HyperLink lnkFlag;
        protected global::System.Web.UI.WebControls.HyperLink lnkPolls;
        protected global::System.Web.UI.WebControls.HyperLink lnkReports;
        protected global::System.Web.UI.WebControls.HyperLink lnkTransparency;
    }
}
