//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalTransparencySystem.Modules.Dashboard
{
    public partial class UserDashboard
    {
        protected global::System.Web.UI.WebControls.Literal litFirstName;
        protected global::System.Web.UI.WebControls.Literal litSubtitle;
        protected global::System.Web.UI.WebControls.Literal litLastUpdated;
        protected global::System.Web.UI.WebControls.Panel pnlMeetingsMetric;
        protected global::System.Web.UI.WebControls.Literal litMyMeetings;
        protected global::System.Web.UI.WebControls.Literal litUpcomingMeetings;
        protected global::System.Web.UI.WebControls.Panel pnlNotificationsMetric;
        protected global::System.Web.UI.WebControls.Literal litUnreadNotifications;
        protected global::System.Web.UI.WebControls.Literal litTotalFeedback;
        protected global::System.Web.UI.WebControls.Literal litResolvedFeedback;
        protected global::System.Web.UI.WebControls.Literal litPendingFeedback;
        protected global::System.Web.UI.WebControls.Literal litTasksCompleted;
        protected global::System.Web.UI.WebControls.Literal litTasksInProgress;
        protected global::System.Web.UI.WebControls.Literal litTasksPending;
        protected global::System.Web.UI.WebControls.Literal litTasksDelayed;
        protected global::System.Web.UI.WebControls.Literal litDecisionsProposed;
        protected global::System.Web.UI.WebControls.Literal litDecisionsUnderReview;
        protected global::System.Web.UI.WebControls.Literal litDecisionsApproved;
        protected global::System.Web.UI.WebControls.Literal litDecisionsRejected;
        protected global::System.Web.UI.WebControls.Literal litDecisionsCompleted;
        protected global::System.Web.UI.WebControls.Button btnFilterAll;
        protected global::System.Web.UI.WebControls.Button btnFilterPending;
        protected global::System.Web.UI.WebControls.Button btnFilterInProgress;
        protected global::System.Web.UI.WebControls.Button btnFilterCompleted;
        protected global::System.Web.UI.WebControls.Button btnFilterLate;
        protected global::System.Web.UI.WebControls.Panel pnlTaskTable;
        protected global::System.Web.UI.WebControls.Repeater rptMyTasks;
        protected global::System.Web.UI.WebControls.Panel pnlNoTasks;
        protected global::System.Web.UI.WebControls.Panel pnlTaskFooter;
        protected global::System.Web.UI.WebControls.Panel pnlReportsSection;
        protected global::System.Web.UI.WebControls.HyperLink lnkViewReports;
        protected global::System.Web.UI.WebControls.Literal litReportEvents;
        protected global::System.Web.UI.WebControls.Literal litReportTasks;
        protected global::System.Web.UI.WebControls.Literal litReportOverdue;
        protected global::System.Web.UI.WebControls.Panel pnlMeetingsSection;
        protected global::System.Web.UI.WebControls.HyperLink lnkViewAllMeetings;
        protected global::System.Web.UI.WebControls.Repeater rptMyMeetings;
        protected global::System.Web.UI.WebControls.HyperLink lnkTaskWorkspaces;
        protected global::System.Web.UI.WebControls.HyperLink lnkSubmitFeedback;
        protected global::System.Web.UI.WebControls.HyperLink lnkViewPolls;
        protected global::System.Web.UI.WebControls.Panel pnlQuickMeetings;
        protected global::System.Web.UI.WebControls.HyperLink lnkQuickMeetings;
        protected global::System.Web.UI.WebControls.Panel pnlQuickReports;
        protected global::System.Web.UI.WebControls.HyperLink lnkQuickReports;
        protected global::System.Web.UI.WebControls.HyperLink lnkViewTransparency;
        protected global::System.Web.UI.WebControls.HyperLink lnkMyProfile;
        protected global::System.Web.UI.WebControls.Repeater rptRecentActivity;
        protected global::System.Web.UI.WebControls.Panel pnlInvitations;
        protected global::System.Web.UI.WebControls.Repeater rptInvitations;
        protected global::System.Web.UI.WebControls.Panel pnlSuspendedBanner;
        protected global::System.Web.UI.WebControls.Literal litSuspendedBanner;
        protected global::System.Web.UI.WebControls.Panel pnlIdentityBanner;
        protected global::System.Web.UI.WebControls.Label lblIdentityBanner;
        protected global::System.Web.UI.WebControls.HyperLink lnkVerifyIdentity;
    }
}
