//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalTransparencySystem.Modules.UserPolls
{
    public partial class UserPolls
    {
        protected global::System.Web.UI.WebControls.Panel pnlVoteMessage;
        protected global::System.Web.UI.WebControls.Literal litVoteMessage;
        protected global::System.Web.UI.WebControls.Repeater rptActivePolls;
        protected global::System.Web.UI.WebControls.Panel pnlNoActivePolls;
        protected global::System.Web.UI.WebControls.Repeater rptPastPolls;
    }
}
