//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalTransparencySystem.Modules.UserTasks
{
    public partial class TaskPreview
    {
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spanStatus;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spanPriority;
        protected global::System.Web.UI.WebControls.Literal litTaskTitle;
        protected global::System.Web.UI.WebControls.Literal litDescription;
        protected global::System.Web.UI.WebControls.Literal litPublicSummary;
        protected global::System.Web.UI.WebControls.Literal litDueDate;
        protected global::System.Web.UI.WebControls.Literal litEvent;
    }
}
