//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalTransparencySystem.Modules.UserTasks
{
    public partial class UserTasks
    {
        protected global::System.Web.UI.WebControls.Button btnFilterAll;
        protected global::System.Web.UI.WebControls.Button btnFilterPending;
        protected global::System.Web.UI.WebControls.Button btnFilterInProgress;
        protected global::System.Web.UI.WebControls.Button btnFilterCompleted;
        protected global::System.Web.UI.WebControls.Button btnFilterLate;
        protected global::System.Web.UI.WebControls.Literal litTotal;
        protected global::System.Web.UI.WebControls.Literal litPending;
        protected global::System.Web.UI.WebControls.Literal litInProgress;
        protected global::System.Web.UI.WebControls.Literal litCompleted;
        protected global::System.Web.UI.WebControls.Repeater rptTasks;
        protected global::System.Web.UI.WebControls.Panel pnlNoTasks;
        protected global::System.Web.UI.WebControls.Label lblPageInfo;
        protected global::System.Web.UI.WebControls.Button btnPrev;
        protected global::System.Web.UI.WebControls.Button btnNext;
    }
}
