//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalTransparencySystem.Modules.TaskWorkspaces
{
    public partial class TaskWorkspace
    {
        protected global::System.Web.UI.WebControls.Panel pnlInternal;
        protected global::System.Web.UI.WebControls.Panel pnlAccessDenied;
        protected global::System.Web.UI.WebControls.HyperLink lnkScheduleMeeting;
        protected global::System.Web.UI.WebControls.Literal litTaskTitle;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spanStatus;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spanPriority;
        protected global::System.Web.UI.WebControls.Panel pnlViewOnly;
        protected global::System.Web.UI.WebControls.Literal litDescription;
        protected global::System.Web.UI.WebControls.Panel pnlDeadlineRisk;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spanRiskBadge;
        protected global::System.Web.UI.WebControls.Literal litRiskTitle;
        protected global::System.Web.UI.WebControls.Literal litRiskMessage;
        protected global::System.Web.UI.WebControls.Panel pnlDeadlineActions;
        protected global::System.Web.UI.WebControls.TextBox txtExtendDue;
        protected global::System.Web.UI.WebControls.Button btnExtendDue;
        protected global::System.Web.UI.WebControls.HyperLink lnkRedistribute;
        protected global::System.Web.UI.WebControls.Literal litDueDate;
        protected global::System.Web.UI.WebControls.Literal litEvent;
        protected global::System.Web.UI.WebControls.Label lblWorkflowMessage;
        protected global::System.Web.UI.WebControls.Panel pnlReview;
        protected global::System.Web.UI.WebControls.TextBox txtReviewComment;
        protected global::System.Web.UI.WebControls.Button btnApprove;
        protected global::System.Web.UI.WebControls.Button btnRequestChanges;
        protected global::System.Web.UI.WebControls.Panel pnlWorkerUpdate;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.TextBox txtComment;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlPublicSummaryField;
        protected global::System.Web.UI.WebControls.TextBox txtPublicSummary;
        protected global::System.Web.UI.WebControls.FileUpload fuEvidence;
        protected global::System.Web.UI.WebControls.Button btnSubmitUpdate;
        protected global::System.Web.UI.WebControls.Label lblSubmitMessage;
        protected global::System.Web.UI.WebControls.Panel pnlSharedComments;
        protected global::System.Web.UI.WebControls.Repeater rptSharedComments;
        protected global::System.Web.UI.WebControls.Panel pnlNoSharedComments;
        protected global::System.Web.UI.WebControls.TextBox txtSharedComment;
        protected global::System.Web.UI.WebControls.Button btnAddSharedComment;
        protected global::System.Web.UI.WebControls.Repeater rptHistory;
        protected global::System.Web.UI.WebControls.Panel pnlNoUpdates;
        protected global::System.Web.UI.WebControls.Literal litUpdateCount;
        protected global::System.Web.UI.WebControls.Panel pnlAssign;
        protected global::System.Web.UI.WebControls.CheckBoxList cblAssignees;
        protected global::System.Web.UI.WebControls.Button btnSaveAssignees;
        protected global::System.Web.UI.WebControls.Repeater rptRoster;
        protected global::System.Web.UI.WebControls.Panel pnlNoRoster;
        protected global::System.Web.UI.WebControls.Literal litCurrentPublicSummary;
        protected global::System.Web.UI.WebControls.Repeater rptAttachments;
        protected global::System.Web.UI.WebControls.Panel pnlNoAttachments;
    }
}
