//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalTransparencySystem.Modules.TaskWorkspaces
{
    public partial class TaskWorkspaces
    {
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlPendingInvitations;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlPendingCount;
        protected global::System.Web.UI.WebControls.Panel pnlNoPending;
        protected global::System.Web.UI.WebControls.Repeater rptPending;
        protected global::System.Web.UI.WebControls.Panel pnlNoEvents;
        protected global::System.Web.UI.WebControls.Repeater rptEventWorkspaces;
        protected global::System.Web.UI.WebControls.Panel pnlNoAccepted;
        protected global::System.Web.UI.WebControls.Repeater rptWorkspaces;
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
