//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalTransparencySystem.Modules.Reports
{

    public partial class LoginHistory
    {

        protected global::System.Web.UI.WebControls.HyperLink lnkBackToReports;

        protected global::System.Web.UI.WebControls.Button btnExport;

        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        protected global::System.Web.UI.WebControls.TextBox txtDate;

        protected global::System.Web.UI.WebControls.TextBox txtStartTime;

        protected global::System.Web.UI.WebControls.TextBox txtEndTime;

        protected global::System.Web.UI.WebControls.Button btnSearch;

        protected global::System.Web.UI.WebControls.Button btnClear;

        protected global::System.Web.UI.WebControls.Literal litRecordCount;

        protected global::System.Web.UI.WebControls.Repeater rptLoginHistory;

        protected global::System.Web.UI.WebControls.Panel pnlNoResults;
    }
}
